function tpl = M1()
%M1  模板定义：匀强磁场中的带电粒子
%
% 说明
%   - 本文件只描述模板元数据，不做参数计算/物理计算。
%   - 参数定义由 params.schema_get(tpl.schemaKey) 提供。

tpl = struct( ...
    "id", "M1", ...
    "title", "匀强磁场中的带电粒子", ...
    "group", "磁场与粒子", ...
    "engineKey", "particle", ...
    "schemaKey", "particle" ...
);

end
