function tpl = M4()
%M4  模板定义：速度选择器（匀强 E 与匀强 B 交叉场）
%
% 说明
%   - M4 使用独立 selector 引擎键，便于与 M1/M5（纯磁场粒子）分离
%   - 参数定义由 params.schema_get("selector") 提供
%   - 场景渲染会叠加速度选择器极板与电场方向标识

tpl = struct( ...
    "id", "M4", ...
    "title", "交叉场中的速度选择器", ...
    "group", "磁场与粒子", ...
    "engineKey", "selector", ...
    "schemaKey", "selector" ...
);

end
