function tpl = M5()
%M5  模板定义：质谱仪（右半有界磁场 + 左侧狭缝入口）
%
% 说明
%   - M5 与 M1/M2 共用粒子引擎（engineKey=particle）
%   - 通过模板预设与参数约束固定“右半磁场”几何语义
%   - 具体场景外观（左侧粗线/小孔）在 viz.renderScene 中绘制

tpl = struct( ...
    "id", "M5", ...
    "title", "质谱仪（右半磁场）", ...
    "group", "磁场与粒子", ...
    "engineKey", "particle", ...
    "schemaKey", "particle" ...
);

end
