function tpl = R()
%R  模板定义：导轨切割磁感线（R 系列统一模板）
%
% 说明
%   - R1/R2/R3 统一为同一个模板入口
%   - 具体场景差异通过参数切换实现（如 loopClosed/driveEnabled）

tpl = struct( ...
    "id", "R", ...
    "title", "导体棒切割磁感线", ...
    "group", "电磁感应与导轨", ...
    "engineKey", "rail", ...
    "schemaKey", "rail" ...
);

end

