function tpl = R1()
%R1  模板定义：单导体棒切割磁感线（导轨场景）
%
% 说明
%   - R1 先实现最小闭环：导体棒匀速运动 + 感应电动势输出
%   - 参数定义由 params.schema_get("rail") 提供
%   - 后续 R2/R3/R4 在同一类场景上扩展闭合回路与阻尼动力学

tpl = struct( ...
    "id", "R1", ...
    "title", "单导体棒切割磁感线", ...
    "group", "电磁感应与导轨", ...
    "engineKey", "rail", ...
    "schemaKey", "rail" ...
);

end

