function tpl = R2LC()
%R2LC  模板定义：导轨切割磁感线（外力驱动 + 闭合回路 + 电容或电感）
%
% 说明
%   - 与 R1 共用 rail 参数结构与引擎
%   - 在模板默认参数上开启 driveEnabled/loopClosed，用于演示动力学平衡过程

tpl = struct( ...
    "id", "R2LC", ...
    "title", "导体棒切割磁感线（电容电感）", ...
    "group", "电磁感应与导轨", ...
    "engineKey", "rail", ...
    "schemaKey", "rail" ...
);

end
