function tpl = R5()
%R5  模板定义：双导体棒导轨模型（A/B 双棒）
%
% 说明
%   - R5 作为独立模板，不并入 R 与 R8。
%   - 引擎仍复用 rail 主链路，但在 step/reset 内走 R5 专用分支。

tpl = struct( ...
    "id", "R5", ...
    "title", "双导体棒导轨模型", ...
    "group", "电磁感应与导轨", ...
    "engineKey", "rail", ...
    "schemaKey", "rail" ...
);

end

