function tpl = R8()
%R8  模板定义：线框在磁场中的运动
%
% 说明
%   - R8 作为独立模板注册，不并入 R 模板
%   - 当前沿用 rail 引擎与 rail 参数 schema（后续可独立为 frame）

tpl = struct( ...
    "id", "R8", ...
    "title", "线框在磁场中的运动", ...
    "group", "电磁感应与导轨", ...
    "engineKey", "rail", ...
    "schemaKey", "rail" ...
);

end
